language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - easy_install -U setuptools
    - pip install requests tornado
    - pip install .
script:
    - py.test
