site_name: SnakeViz
site_url: https://jiffyclub.github.io/snakeviz/
repo_url: https://github.com/jiffyclub/snakeviz/
site_description: >
    SnakeViz is a browser based graphical viewer for the output of
    Python's cProfile module.
site_author: Matt Davis (jiffyclub)
site_favicon: favicon.ico
theme: readable
markdown_extensions:
    - smarty
